# Generated by Django 5.2.7 on 2025-10-11 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.IntegerField(choices=[(0, 'Dia'), (1, 'Tarde'), (2, 'Noche')])),
                ('subdivision', models.IntegerField(choices=[(0, '1'), (1, '2'), (2, '3')])),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.calendar')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event')),
            ],
        ),
    ]
