# Generated by Django 5.2.7 on 2025-10-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_eventconnector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventconnector',
            name='division',
            field=models.SmallIntegerField(choices=[(0, 'Dia'), (1, 'Tarde'), (2, 'Noche')]),
        ),
        migrations.AlterField(
            model_name='eventconnector',
            name='subdivision',
            field=models.SmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2')]),
        ),
    ]
