# Generated by Django 5.2.7 on 2025-10-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_eventconnector_subdivision_eventconnector_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventconnector',
            name='day',
            field=models.SmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miercoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sab y Dom')]),
        ),
        migrations.AlterField(
            model_name='eventconnector',
            name='division',
            field=models.SmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2')]),
        ),
        migrations.AlterField(
            model_name='eventconnector',
            name='group',
            field=models.SmallIntegerField(choices=[(0, 'Dia'), (1, 'Tarde'), (2, 'Noche')]),
        ),
    ]
