# Generated by Django 5.2.7 on 2025-10-12 03:03

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_calendar_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='photo',
            field=models.ImageField(default='static/images/default_calendar.png', upload_to=main.models.calendar_photo_path),
        ),
    ]
