# Generated by Django 5.2.7 on 2025-10-15 21:33

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_calendar_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventconnector',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to=main.models.calendar_photo_path),
        ),
    ]
