# Generated by Django 5.2.7 on 2025-10-19 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_event_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='visible',
        ),
    ]
