# Generated by Django 5.2.7 on 2025-11-05 02:35

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_event_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='photo_path',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(default='default.png', upload_to=main.models.event_photo_path),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=main.models.calendar_photo_path),
        ),
        migrations.AlterField(
            model_name='eventconnector',
            name='day',
            field=models.SmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miercoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sabado'), (6, 'Domingo')]),
        ),
    ]
